# ~/.tmuxinator/k2m.yml

project_name: k2m
project_root: ~/Code/kikuchat2-mobile
socket_path: /tmp/tmux-pair-session
windows:
  - editor:
      layout: 8087,238x60,0,0[238x44,0,0,0,238x15,0,45,5]
      panes:
        - vim
        - alloy compile --config platform=ios && tishadow run -p 4444
  - shell: git remote update origin; git pull --rebase origin
  - console/server:
      layout: even-vertical
      panes:
        - wt tishadow repl -p 4444
        - wt tishadow server -p 4444
  - starting: chmod 777 /tmp/tmux-pair-session; tmux set-window-option -t $SESSION:3 monitor-activity off; tmux set-window-option -t $SESSION:4 monitor-activity off; sleep 2; kr; kz; exit; exit; exit
